### ISSUE TITLE
Song filters still appear after pressing play

### ISSUE THREAD

**Issue by xFutuxe** [kinsi55/BeatSaber_BetterSongSearch#3] opened 2021-09-25 19:13 UTC
After downloading a song and pressing play on song details the search filters remain active 

![image](https://user-images.githubusercontent.com/65718499/134783579-e201ea1c-67ff-48a5-9af3-2e26760e5e27.png)

**Comment by kinsi55** [comment] 2021-09-25 19:15
Is this on 1.18?

**Comment by xFutuxe** [comment] 2021-09-25 19:15
Yes

**Comment by kinsi55** [comment] 2021-09-25 19:17
I'm unable to reproduce that, can you start the game, reproduce the bug, close the game and attach your _latest.log from your logs folder?

**Comment by xFutuxe** [comment] 2021-09-25 19:17
added issue to wrong repo at start sorry about that lol

**Comment by xFutuxe** [comment] 2021-09-25 19:20
Here 👍 

[_latest.log](https://github.com/kinsi55/BeatSaber_BetterSongSearch/files/7230248/_latest.log)

**Comment by kinsi55** [comment] 2021-09-25 19:24
Seems to be a regression due to changes in BSML. I'll talk with the person who did those

**Comment by xFutuxe** [comment] 2021-09-25 19:26
👍

**Comment by kinsi55** [comment] 2021-09-25 21:23
This is fixed in the upcoming update for BeatSaberMarkupLanguage (BSML), ty for the report

**Closed by kinsi55** 2021-09-25 21:23 UTC
